 'Entorhinal area': 'ECT',
 'Entorhinal area lateral part': 'ECT',
 'Entorhinal area lateral part layer 1': 'ECT',
 'Entorhinal area lateral part layer 2': 'ECT',
 'Entorhinal area lateral part layer 2/3': 'ECT',
 'Entorhinal area lateral part layer 2a': 'ECT',
 'Entorhinal area lateral part layer 2b': 'ECT',
 'Entorhinal area lateral part layer 3': 'ECT',
 'Entorhinal area lateral part layer 4': 'ECT',
 'Entorhinal area lateral part layer 4/5': 'ECT',
 'Entorhinal area lateral part layer 5': 'ECT',
 'Entorhinal area lateral part layer 5/6': 'ECT',
 'Entorhinal area lateral part layer 6a': 'ECT',
 'Entorhinal area lateral part layer 6b': 'ECT',
 'Entorhinal area medial part dorsal zone': 'ECT',
 'Entorhinal area medial part dorsal zone layer 1': 'ECT',
 'Entorhinal area medial part dorsal zone layer 2': 'ECT',
 'Entorhinal area medial part dorsal zone layer 2a': 'ECT',
 'Entorhinal area medial part dorsal zone layer 2b': 'ECT',
 'Entorhinal area medial part dorsal zone layer 3': 'ECT',
 'Entorhinal area medial part dorsal zone layer 4': 'ECT',
 'Entorhinal area medial part dorsal zone layer 5': 'ECT',
 'Entorhinal area medial part dorsal zone layer 5/6': 'ECT',
 'Entorhinal area medial part dorsal zone layer 6': 'ECT',
 'Entorhinal area medial part ventral zone': 'ECT',
 'Entorhinal area medial part ventral zone layer 1': 'ECT',
 'Entorhinal area medial part ventral zone layer 2': 'ECT',
 'Entorhinal area medial part ventral zone layer 3': 'ECT',
 'Entorhinal area medial part ventral zone layer 4': 'ECT',
 'Entorhinal area medial part ventral zone layer 5/6': 'ECT',